INSERT INTO MORTGAGE_RATE (ID, MATURITY_PERIOD, INTEREST_RATE, LAST_UPDATE) VALUES (1, 30, 7.18, CURRENT_TIMESTAMP());
INSERT INTO MORTGAGE_RATE (ID, MATURITY_PERIOD, INTEREST_RATE, LAST_UPDATE) VALUES (2, 20, 7.1, CURRENT_TIMESTAMP());
INSERT INTO MORTGAGE_RATE (ID, MATURITY_PERIOD, INTEREST_RATE, LAST_UPDATE) VALUES (3, 15, 6.35, CURRENT_TIMESTAMP());
INSERT INTO MORTGAGE_RATE (ID, MATURITY_PERIOD, INTEREST_RATE, LAST_UPDATE) VALUES (4, 10, 6.45, CURRENT_TIMESTAMP());