INSERT INTO MORTGAGE_RATE (ID, MATURITY_PERIOD, INTEREST_RATE, LAST_UPDATE) VALUES (1, 30, 4.0, CURRENT_TIMESTAMP());
INSERT INTO MORTGAGE_RATE (ID, MATURITY_PERIOD, INTEREST_RATE, LAST_UPDATE) VALUES (2, 20, 3.75, CURRENT_TIMESTAMP());
INSERT INTO MORTGAGE_RATE (ID, MATURITY_PERIOD, INTEREST_RATE, LAST_UPDATE) VALUES (3, 15, 3.5, CURRENT_TIMESTAMP());
INSERT INTO MORTGAGE_RATE (ID, MATURITY_PERIOD, INTEREST_RATE, LAST_UPDATE) VALUES (4, 10, 3.0, CURRENT_TIMESTAMP());